tasks:
  - type: Faucet
    probability: 5
  - type: Transfer
    probability: 2
  - type: Delegate
    probability: 3
  - type: Unbond
    probability: 3
  - type: Withdraw
    probability: 2

settings:
  dry_run: false
  total_tx: 200
