STATUS_ENDPOINT = 'status'
VALID_TRANSACTION_OUTPUT = 'Transaction is valid.'
INVALID_TRANSACTION_OUTPUT = 'Transaction is invalid.'
INVALID_TRANSACTION_EXECUTION_OUTPUT = 'Error trying to apply a transaction'
ACCOUNT_FORMAT = 'lt-account'
TOKENS = ['XAN', 'DOT', 'ETH', 'BTC']
TOKEN_PROBABILITIES = [70, 10, 10, 10]
LOCAL_LEDGER_ADDRESS = "127.0.0.1:27657"
